runtime: go
api_version: go1
application: fsq-go-explore

env_variables:
  FSQ_CLIENT_ID: 'NXEXOLFZV3GVPLSNRS3CXCVU2HPDWYIAH42A3ZBJPE4UL2VS'
  FSQ_CLIENT_SECRET: 'WZEU1OWOTTOOK5FSZ53FH5GQ1PZZIUIZUWMFI1SOCABYAZLN'
  FSQ_VERSION: 'YYYYMMDD'

handlers:
- url: /.*
  script: _go_main
